/* Decoder coverage: mp3, wav, ogg, flac.
 *
 * webaudio-node's own decoder file is not built (it hard-requires opus and
 * libxaac), so shim/sg_audio_decode.cpp uses the same header-only libraries
 * for these four. This checks each one actually decodes AND produces audible
 * samples -- a decoder that returns the right frame count and silence would
 * otherwise pass unnoticed.
 *
 * The four inputs are generated by scripts/make-decode-fixtures.sh from one
 * source, so identical content arrives through four different code paths and
 * the durations must agree.
 *
 * Usage: decodetest <fixtureDir>
 */
import * as ffi from "../host/ffi.js";
import {
  OfflineAudioContext, closeAudio, AudioContext, AudioBuffer,
} from "../web/audio/context.js";

let failures = 0;
let checks = 0;

function check(ok: boolean, what: string): void {
  checks += 1;
  if (!ok) { console.log(`FAIL: ${what}`); failures += 1; }
}

const RATE = 48000;
const EXPECTED_SEC = 3;

/** Renders a decoded buffer and reports its peak, to prove it is not silence. */
function peakOf(ctx: AudioContext, buf: AudioBuffer, outPath: string): number {
  const src = ctx.createBufferSource();
  src.buffer = buf;
  src.connect(ctx.destination);
  src.start(0);
  if (ctx.renderToFile(outPath, 4800) !== 0) return -1;
  src.disconnect(ctx.destination);

  // Read the float WAV back and find the peak.
  const data = readWav(outPath);
  return data;
}

function readWav(path: string): number {
  const buf = readFileSync(path);
  const count = (buf.length - 44) / 4;
  let peak = 0;
  for (let i = 0; i < count; i++) {
    const o = 44 + i * 4;
    const bits = ((buf[o + 3] << 24) | (buf[o + 2] << 16) | (buf[o + 1] << 8) | buf[o]) >>> 0;
    const v = f32FromBits(bits);
    const a = v < 0 ? -v : v;
    if (a > peak) peak = a;
  }
  return peak;
}

function f32FromBits(bits: number): number {
  const sign = (bits >>> 31) !== 0 ? -1 : 1;
  const exp = (bits >>> 23) & 0xff;
  const frac = bits & 0x7fffff;
  if (exp === 0) return sign * frac * 1.4012984643248171e-45;
  if (exp === 255) return 0;
  let m = 1 + frac / 8388608;
  let e = exp - 127;
  while (e > 0) { m *= 2; e -= 1; }
  while (e < 0) { m /= 2; e += 1; }
  return sign * m;
}

import { readFileSync } from "node:fs";

function main(): void {
  const args = process.argv;
  const dir = args.length > 2 ? args[2] : "test/out";

  const ctx = OfflineAudioContext.create(2, 0, RATE);
  if (ctx === null) { console.log("FATAL: offline context"); process.exit(2); }

  const formats: string[] = ["mp3", "wav", "ogg", "flac"];
  for (let i = 0; i < formats.length; i++) {
    const fmt = formats[i];
    const path = `${dir}/fmt.${fmt}`;
    const buf = ctx.decodeAudioFile(path);

    if (buf === null) {
      console.log(`FAIL: ${fmt} did not decode`);
      failures += 1;
      checks += 1;
      continue;
    }

    const peak = peakOf(ctx, buf, `${dir}/decoded-${fmt}.wav`);
    console.log(`${fmt}: ${buf.duration.toFixed(2)}s ${buf.numberOfChannels}ch ` +
                `@${buf.sampleRate}Hz peak=${peak.toFixed(4)}`);

    /* Lossy formats pad slightly, so the duration is a window rather than an
     * equality; the point is that all four agree on the same source. */
    check(buf.duration > EXPECTED_SEC - 0.3 && buf.duration < EXPECTED_SEC + 0.3,
          `${fmt} duration ${buf.duration}, want ~${EXPECTED_SEC}s`);
    check(buf.numberOfChannels === 2, `${fmt} is ${buf.numberOfChannels}ch, want 2`);
    check(buf.sampleRate === RATE, `${fmt} is ${buf.sampleRate}Hz, want ${RATE}`);
    // The check that matters: a decoder can report perfect metadata and
    // hand back silence.
    check(peak > 0.01, `${fmt} rendered peak ${peak}, want audible`);
  }

  /* An unsupported extension must FAIL rather than mis-parse: every decoder
   * here will happily read another format's header and emit noise. */
  const bogus = ctx.decodeAudioFile(`${dir}/fmt.xyz`);
  check(bogus === null, "an unsupported extension is rejected");

  closeAudio();
  console.log(`\ndecode test: ${checks - failures}/${checks} checks passed`);
  process.exit(failures === 0 ? 0 : 1);
}

main();
