/* GENERATED by codegen/gen-gl.js from the pinned GLES3 header. Do not edit.
 *
 * The raw GLES3 surface. This is NOT the WebGL2 API: it is the flat C
 * binding the WebGL2RenderingContext shim is written against. Games never
 * import this.
 *
 * Two shapes appear below. Most entry points are declared directly, since
 * GL names are u32 and the arguments are scalars, so they bind with no C
 * wrapper. Float-taking ones go through sg_gl_* wrappers that narrow
 * double -> GLfloat at the boundary (docs/FFI-SHIM.md explains why f64
 * cannot be passed straight through).
 */

declare function glActiveTexture(a0: number): void;
declare function glAttachShader(a0: number, a1: number): void;
declare function glBindBuffer(a0: number, a1: number): void;
declare function glBindFramebuffer(a0: number, a1: number): void;
declare function glBindRenderbuffer(a0: number, a1: number): void;
declare function glBindTexture(a0: number, a1: number): void;
declare function glBlendEquation(a0: number): void;
declare function glBlendEquationSeparate(a0: number, a1: number): void;
declare function glBlendFunc(a0: number, a1: number): void;
declare function glBlendFuncSeparate(a0: number, a1: number, a2: number, a3: number): void;
declare function glCheckFramebufferStatus(a0: number): number;
declare function glClear(a0: number): void;
declare function glClearStencil(a0: number): void;
declare function glColorMask(a0: number, a1: number, a2: number, a3: number): void;
declare function glCompileShader(a0: number): void;
declare function glCopyTexImage2D(a0: number, a1: number, a2: number, a3: number, a4: number, a5: number, a6: number, a7: number): void;
declare function glCopyTexSubImage2D(a0: number, a1: number, a2: number, a3: number, a4: number, a5: number, a6: number, a7: number): void;
declare function glCreateProgram(): number;
declare function glCreateShader(a0: number): number;
declare function glCullFace(a0: number): void;
declare function glDeleteProgram(a0: number): void;
declare function glDeleteShader(a0: number): void;
declare function glDepthFunc(a0: number): void;
declare function glDepthMask(a0: number): void;
declare function glDetachShader(a0: number, a1: number): void;
declare function glDisable(a0: number): void;
declare function glDisableVertexAttribArray(a0: number): void;
declare function glDrawArrays(a0: number, a1: number, a2: number): void;
declare function glEnable(a0: number): void;
declare function glEnableVertexAttribArray(a0: number): void;
declare function glFinish(): void;
declare function glFlush(): void;
declare function glFramebufferRenderbuffer(a0: number, a1: number, a2: number, a3: number): void;
declare function glFramebufferTexture2D(a0: number, a1: number, a2: number, a3: number, a4: number): void;
declare function glFrontFace(a0: number): void;
declare function glGenerateMipmap(a0: number): void;
declare function glGetError(): number;
declare function glHint(a0: number, a1: number): void;
declare function glIsBuffer(a0: number): number;
declare function glIsEnabled(a0: number): number;
declare function glIsFramebuffer(a0: number): number;
declare function glIsProgram(a0: number): number;
declare function glIsRenderbuffer(a0: number): number;
declare function glIsShader(a0: number): number;
declare function glIsTexture(a0: number): number;
declare function glLinkProgram(a0: number): void;
declare function glPixelStorei(a0: number, a1: number): void;
declare function glReleaseShaderCompiler(): void;
declare function glRenderbufferStorage(a0: number, a1: number, a2: number, a3: number): void;
declare function glScissor(a0: number, a1: number, a2: number, a3: number): void;
declare function glStencilFunc(a0: number, a1: number, a2: number): void;
declare function glStencilFuncSeparate(a0: number, a1: number, a2: number, a3: number): void;
declare function glStencilMask(a0: number): void;
declare function glStencilMaskSeparate(a0: number, a1: number): void;
declare function glStencilOp(a0: number, a1: number, a2: number): void;
declare function glStencilOpSeparate(a0: number, a1: number, a2: number, a3: number): void;
declare function glTexParameteri(a0: number, a1: number, a2: number): void;
declare function glUniform1i(a0: number, a1: number): void;
declare function glUniform2i(a0: number, a1: number, a2: number): void;
declare function glUniform3i(a0: number, a1: number, a2: number, a3: number): void;
declare function glUniform4i(a0: number, a1: number, a2: number, a3: number, a4: number): void;
declare function glUseProgram(a0: number): void;
declare function glValidateProgram(a0: number): void;
declare function glViewport(a0: number, a1: number, a2: number, a3: number): void;
declare function glReadBuffer(a0: number): void;
declare function glCopyTexSubImage3D(a0: number, a1: number, a2: number, a3: number, a4: number, a5: number, a6: number, a7: number, a8: number): void;
declare function glIsQuery(a0: number): number;
declare function glBeginQuery(a0: number, a1: number): void;
declare function glEndQuery(a0: number): void;
declare function glUnmapBuffer(a0: number): number;
declare function glBlitFramebuffer(a0: number, a1: number, a2: number, a3: number, a4: number, a5: number, a6: number, a7: number, a8: number, a9: number): void;
declare function glRenderbufferStorageMultisample(a0: number, a1: number, a2: number, a3: number, a4: number): void;
declare function glFramebufferTextureLayer(a0: number, a1: number, a2: number, a3: number, a4: number): void;
declare function glFlushMappedBufferRange(a0: number, a1: number, a2: number): void;
declare function glBindVertexArray(a0: number): void;
declare function glIsVertexArray(a0: number): number;
declare function glBeginTransformFeedback(a0: number): void;
declare function glEndTransformFeedback(): void;
declare function glBindBufferRange(a0: number, a1: number, a2: number, a3: number, a4: number): void;
declare function glBindBufferBase(a0: number, a1: number, a2: number): void;
declare function glVertexAttribI4i(a0: number, a1: number, a2: number, a3: number, a4: number): void;
declare function glVertexAttribI4ui(a0: number, a1: number, a2: number, a3: number, a4: number): void;
declare function glUniform1ui(a0: number, a1: number): void;
declare function glUniform2ui(a0: number, a1: number, a2: number): void;
declare function glUniform3ui(a0: number, a1: number, a2: number, a3: number): void;
declare function glUniform4ui(a0: number, a1: number, a2: number, a3: number, a4: number): void;
declare function glCopyBufferSubData(a0: number, a1: number, a2: number, a3: number, a4: number): void;
declare function glUniformBlockBinding(a0: number, a1: number, a2: number): void;
declare function glDrawArraysInstanced(a0: number, a1: number, a2: number, a3: number): void;
declare function glIsSampler(a0: number): number;
declare function glBindSampler(a0: number, a1: number): void;
declare function glSamplerParameteri(a0: number, a1: number, a2: number): void;
declare function glVertexAttribDivisor(a0: number, a1: number): void;
declare function glBindTransformFeedback(a0: number, a1: number): void;
declare function glIsTransformFeedback(a0: number): number;
declare function glPauseTransformFeedback(): void;
declare function glResumeTransformFeedback(): void;
declare function glProgramParameteri(a0: number, a1: number, a2: number): void;
declare function glTexStorage2D(a0: number, a1: number, a2: number, a3: number, a4: number): void;
declare function glTexStorage3D(a0: number, a1: number, a2: number, a3: number, a4: number, a5: number): void;

/* Float entry points, through narrowing wrappers. */
declare function sg_gl_blend_color(a0: number, a1: number, a2: number, a3: number): void;
declare function sg_gl_clear_color(a0: number, a1: number, a2: number, a3: number): void;
declare function sg_gl_clear_depthf(a0: number): void;
declare function sg_gl_depth_rangef(a0: number, a1: number): void;
declare function sg_gl_line_width(a0: number): void;
declare function sg_gl_polygon_offset(a0: number, a1: number): void;
declare function sg_gl_sample_coverage(a0: number, a1: number): void;
declare function sg_gl_tex_parameterf(a0: number, a1: number, a2: number): void;
declare function sg_gl_uniform1f(a0: number, a1: number): void;
declare function sg_gl_uniform2f(a0: number, a1: number, a2: number): void;
declare function sg_gl_uniform3f(a0: number, a1: number, a2: number, a3: number): void;
declare function sg_gl_uniform4f(a0: number, a1: number, a2: number, a3: number, a4: number): void;
declare function sg_gl_vertex_attrib1f(a0: number, a1: number): void;
declare function sg_gl_vertex_attrib2f(a0: number, a1: number, a2: number): void;
declare function sg_gl_vertex_attrib3f(a0: number, a1: number, a2: number, a3: number): void;
declare function sg_gl_vertex_attrib4f(a0: number, a1: number, a2: number, a3: number, a4: number): void;
declare function sg_gl_clear_bufferfi(a0: number, a1: number, a2: number, a3: number): void;
declare function sg_gl_sampler_parameterf(a0: number, a1: number, a2: number): void;
