/* Generate the build entry for a game directory.
 *
 * A game is a DIRECTORY, as in jsgamelauncher: point the build at it and the
 * entry file is found by convention. The generated entry boots the host, lets
 * the game's module body run, then starts the frame loop -- the native
 * equivalent of a page loading a script.
 *
 * Entry resolution mirrors jsgamelauncher's launcher.js:426-433, minus the
 * package.json step (a .ts game has no npm main):
 *
 *     main.ts, src/main.ts, index.ts, src/index.ts, game.ts, src/game.ts
 *
 * index.html is NOT parsed, also matching jsgamelauncher: the canvas size
 * comes from the game's own config, not from an HTML attribute.
 *
 * Usage: node codegen/gen-entry.js <gameDir> [outFile]
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const gameDir = process.argv[2];
if (!gameDir) {
  console.error("usage: gen-entry.js <gameDir> [outFile]");
  process.exit(1);
}

const dir = resolve(gameDir);
if (!existsSync(dir)) {
  console.error(`game directory not found: ${gameDir}`);
  process.exit(1);
}

const TRY_ORDER = [
  ["main.ts"],
  ["src", "main.ts"],
  ["index.ts"],
  ["src", "index.ts"],
  ["game.ts"],
  ["src", "game.ts"],
];

let entry = null;
for (const parts of TRY_ORDER) {
  const candidate = join(dir, ...parts);
  if (existsSync(candidate)) { entry = candidate; break; }
}
if (!entry) {
  console.error(
    `no game entry in ${gameDir}\n` +
      `looked for: ${TRY_ORDER.map((p) => p.join("/")).join(", ")}`,
  );
  process.exit(1);
}

/* Optional per-game config. Deliberately NOT a manifest format: it is the
 * handful of things a page would express in HTML or CSS (canvas size, title)
 * and which the native host has nowhere else to learn. */
let width = 640;
let height = 360;
let title = "scriptc-game";
const cfgPath = join(dir, "game.json");
if (existsSync(cfgPath)) {
  const cfg = JSON.parse(readFileSync(cfgPath, "utf8"));
  if (typeof cfg.width === "number") width = cfg.width;
  if (typeof cfg.height === "number") height = cfg.height;
  if (typeof cfg.title === "string") title = cfg.title;
}

const outFile = process.argv[3] ?? join(dir, ".sg-build", "entry.ts");
mkdirSync(dirname(outFile), { recursive: true });

/** Import specifier from the generated entry to a repo file. */
const specTo = (target) => {
  let rel = relative(dirname(outFile), target).split("\\").join("/");
  if (!rel.startsWith(".")) rel = `./${rel}`;
  return rel.replace(/\.ts$/, ".js");
};

const hostSpec = specTo(join(root, "host/runtime.ts"));
const gameSpec = specTo(entry);

/* The web root as the built binary will see it: relative to the repo so a
 * clone works from any checkout path, with public/ preferred when present
 * (host/resources.ts applies that rule). */
const gameRootLiteral = relative(root, dir).split("\\").join("/");

const text = `/* GENERATED by codegen/gen-entry.js. DO NOT EDIT.
 *
 * Regenerate by building the game: scripts/build.sh <gameDir>
 *
 * The order below is the whole point, and it mirrors a browser page:
 *
 *   1. boot()  opens the window, so a live canvas exists
 *   2. the game module is evaluated -- its top level runs here
 *   3. run()   fires 'load', then drives requestAnimationFrame forever
 *
 * ES imports are HOISTED, so step 2 actually happens before step 1's
 * statement is reached. That is exactly why setup belongs in a 'load'
 * handler (window.onLoad) rather than at a module's top level -- the same
 * rule a page follows.
 */
import { boot, run, HostOptions, optionsFromEnv } from "${hostSpec}";

const opts = optionsFromEnv(new HostOptions());
opts.width = ${width};
opts.height = ${height};
/* The web root, baked in at build time.
 *
 * NOT derived from argv[1]: the binary lives in build/ while its assets live
 * with the source, so deriving the root from the executable's directory
 * silently loads nothing. SG_GAME_DIR overrides for a shipped bundle that
 * sits beside its assets. */
opts.gameDir = process.env["SG_GAME_DIR"] ?? "${gameRootLiteral}";

const brc = boot(opts);
if (brc !== 0) process.exit(brc);

import "${gameSpec}";

process.exit(run(opts));
`;

writeFileSync(outFile, text);
console.log(`gen-entry: ${relative(root, entry)} -> ${relative(root, outFile)} (${width}x${height})`);
