/* Generate the GLES3 binding layer from gl3.h.
 *
 * ONE source of truth (the system GLES3 header) produces two artifacts that
 * cannot drift:
 *
 *   shim/sg_gl_gen.cpp   narrowing wrappers, ONLY where they are needed
 *   host/gl-ffi.ts       the `declare` block + the TS-side wrappers
 *
 * Most of GL needs no shim at all. GL object names are u32 and the bulk of
 * the API is scalars, so those entry points bind straight from the manifest
 * to libGLESv2 with nothing in between (verified in spike/gltest.ts). Three
 * categories are treated differently:
 *
 *   PASSTHROUGH  scalars only, no floats -> direct declare, no C wrapper
 *   NARROW       takes GLfloat -> a wrapper taking doubles, narrowing at
 *                the boundary, because the FFI has no f32 class and
 *                declaring a float API as f64 silently reads garbage (see
 *                docs/FFI-SHIM.md)
 *   MANUAL       pointers -> not emitted; these need real shim code
 *                (out-params, buffer uploads, string returns) and are
 *                hand-written in sg_gl_extra.cpp as the WebGL2 layer needs
 *                them
 *
 * The parser is deliberately dumb, like gen-shim.js: gl3.h is
 * machine-regular, and any signature this cannot classify is REPORTED, not
 * guessed.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const HEADER = process.argv[2] ?? "/usr/include/GLES3/gl3.h";
if (!existsSync(HEADER)) {
  console.error(`gen-gl: no GLES3 header at ${HEADER} (apt install libgles-dev)`);
  process.exit(1);
}

/* GL scalar types -> FFI param classes.
 *
 * GLfloat/GLclampf are deliberately absent: they are what forces a wrapper,
 * and mapping them here would produce the silent-garbage bug. */
const SCALARS = {
  GLenum: "u32", GLuint: "u32", GLbitfield: "u32",
  GLint: "i32", GLsizei: "i32", GLfixed: "i32",
  GLboolean: "u8", GLubyte: "u8", GLbyte: "u8",
  GLshort: "i32", GLushort: "u32",
  GLintptr: "f64", GLsizeiptr: "f64",   // 64-bit on LP64; f64 holds them exactly to 2^53
  GLint64: "f64", GLuint64: "f64",
  void: "void",
};
const FLOATS = new Set(["GLfloat", "GLclampf", "GLdouble", "GLclampd"]);

/** Strips qualifiers and collapses whitespace so a type is one token. */
function normalizeType(raw) {
  return raw.replace(/\bconst\b/g, "").replace(/\s+/g, " ").trim();
}

function parseHeader(text) {
  const out = [];
  const re = /GL_APICALL\s+(.*?)\s*GL_APIENTRY\s+(\w+)\s*\(([^;]*?)\);/gs;
  let m;
  while ((m = re.exec(text)) !== null) {
    const ret = normalizeType(m[1]);
    const name = m[2];
    const argsRaw = normalizeType(m[3]);
    const params = argsRaw === "void" || argsRaw === ""
      ? []
      : argsRaw.split(",").map((a) => {
          const t = normalizeType(a);
          // "GLenum target" / "const void *data" / "GLuint" (unnamed)
          const starCount = (t.match(/\*/g) || []).length;
          const base = t.replace(/\*/g, " ").trim().split(/\s+/)[0];
          return { type: base, pointer: starCount > 0 };
        });
    out.push({ name, ret, params });
  }
  return out;
}

/* GLsync is the ONE GL object that is a pointer rather than a u32 name, so
 * it cannot cross the FFI as a scalar. The five entry points touching it go
 * through a handle table in sg_gl_extra.cpp, hand-written, exactly as the
 * plan calls for. */
const POINTER_OBJECTS = new Set(["GLsync"]);

function classify(fn) {
  if (fn.ret.includes("*") || fn.params.some((p) => p.pointer)) return "manual";
  const all = [fn.ret.replace(/\*/g, "").trim(), ...fn.params.map((p) => p.type)];
  if (all.some((t) => POINTER_OBJECTS.has(t))) return "manual";
  const types = [fn.ret.replace(/\*/g, "").trim(), ...fn.params.map((p) => p.type)];
  if (types.some((t) => FLOATS.has(t))) return "narrow";
  if (types.every((t) => t in SCALARS)) return "passthrough";
  return "unknown";
}

const decls = parseHeader(readFileSync(HEADER, "utf8"));
const buckets = { passthrough: [], narrow: [], manual: [], unknown: [] };
for (const fn of decls) buckets[classify(fn)].push(fn);

if (buckets.unknown.length > 0) {
  console.error("gen-gl: unclassifiable signatures (report, never guess):");
  for (const fn of buckets.unknown.slice(0, 10)) {
    console.error(`  ${fn.ret} ${fn.name}(${fn.params.map((p) => p.type).join(", ")})`);
  }
  process.exit(1);
}

/* ---- shim/sg_gl_gen.cpp: narrowing wrappers only ---- */

const cLines = [
  "/* GENERATED by codegen/gen-gl.js from the pinned GLES3 header. Do not edit. */",
  "/*",
  " * Only the float-taking entry points appear here. Everything else binds",
  " * straight from the manifest with no wrapper at all.",
  " *",
  " * The wrapper exists because scriptc's FFI has no f32 class. Declaring a",
  " * GLfloat-taking function with f64 params is not an approximation: the two",
  " * occupy XMM registers differently, so the callee reinterprets the bits and",
  " * reads garbage. Narrowing at the boundary costs one cvtsd2ss, measured as",
  " * below noise. See docs/FFI-SHIM.md.",
  " */",
  "#include <GLES3/gl3.h>",
  "",
  'extern "C" {',
  "",
];

const tsLines = [
  "/* GENERATED by codegen/gen-gl.js from the pinned GLES3 header. Do not edit.",
  " *",
  " * The raw GLES3 surface. This is NOT the WebGL2 API: it is the flat C",
  " * binding the WebGL2RenderingContext shim is written against. Games never",
  " * import this.",
  " *",
  " * Two shapes appear below. Most entry points are declared directly, since",
  " * GL names are u32 and the arguments are scalars, so they bind with no C",
  " * wrapper. Float-taking ones go through sg_gl_* wrappers that narrow",
  " * double -> GLfloat at the boundary (docs/FFI-SHIM.md explains why f64",
  " * cannot be passed straight through).",
  " */",
  "",
];

function tsParams(fn) {
  return fn.params.map((p, i) => `a${i}: number`).join(", ");
}
function tsReturn(fn) {
  const r = SCALARS[fn.ret] ?? "void";
  return r === "void" ? "void" : "number";
}

for (const fn of buckets.passthrough) {
  tsLines.push(`declare function ${fn.name}(${tsParams(fn)}): ${tsReturn(fn)};`);
}

tsLines.push("");
tsLines.push("/* Float entry points, through narrowing wrappers. */");

for (const fn of buckets.narrow) {
  const wrapper = `sg_gl_${fn.name.replace(/^gl/, "").replace(/([a-z0-9])([A-Z])/g, "$1_$2").toLowerCase()}`;
  const cParams = fn.params
    .map((p, i) => `${FLOATS.has(p.type) ? "double" : p.type} a${i}`)
    .join(", ");
  const callArgs = fn.params
    .map((p, i) => (FLOATS.has(p.type) ? `(${p.type})a${i}` : `a${i}`))
    .join(", ");
  const cRet = fn.ret === "void" ? "void" : fn.ret;
  cLines.push(`${cRet} ${wrapper}(${cParams || "void"}) {`);
  cLines.push(`  ${cRet === "void" ? "" : "return "}${fn.name}(${callArgs});`);
  cLines.push("}");
  cLines.push("");
  tsLines.push(`declare function ${wrapper}(${tsParams(fn)}): ${tsReturn(fn)};`);
}

cLines.push("}  // extern \"C\"");

/* The hand-written shim's entry points need declarations too, and they must
 * come from the SOURCE rather than a second list that can drift. Parsed out
 * of sg_gl_extra.cpp the same way the header is parsed. */
const extraPath = join(root, "shim/sg_gl_extra.cpp");
if (existsSync(extraPath)) {
  const extra = readFileSync(extraPath, "utf8");
  const re = /^(uint32_t|int32_t|double|void)\s+(sg_gl_\w+)\(([^)]*)\)\s*\{/gm;
  let em;
  /* Declared by hand in host/ffi.ts, which is where the host-side GL
   * lifecycle lives (window context, present, screenshot). Emitting them
   * here too would declare the same native symbol twice, which the manifest
   * rejects outright. */
  const seen = new Set(["sg_gl_init_window", "sg_gl_present", "sg_gl_save_png"]);
  tsLines.push("");
  tsLines.push("/* Hand-written shim (shim/sg_gl_extra.cpp): pointers, out-params,");
  tsLines.push(" * strings and bulk uploads -- everything FFI format 1 cannot express");
  tsLines.push(" * as a straight passthrough. */");
  while ((em = re.exec(extra)) !== null) {
    const [, cret, name, args] = em;
    if (seen.has(name)) continue;
    seen.add(name);
    const argList = args.trim() === "void" || args.trim() === "" ? [] : args.split(",");
    // `const uint8_t* x, size_t len` is ONE `bytes`/`string` param in TS.
    const ps = [];
    for (let i = 0; i < argList.length; i++) {
      const a = argList[i].trim();
      if (a.includes("uint8_t*")) {
        /* Both `string` and `bytes` arrive as (const uint8_t*, size_t), so
         * the C signature alone cannot say which. The PARAMETER NAME does:
         * anything called src/name is text (shader source, uniform names),
         * everything else is binary. Mirrors how gen-shim.js reads
         * skia_c.hpp. */
        const isText = /\b(name|src|source|label)\b/.test(a);
        ps.push(`a${ps.length}: ${isText ? "string" : "Buffer"}`);
        i += 1;                       // skip the paired size_t
      } else {
        ps.push(`a${ps.length}: number`);
      }
    }
    const ret = cret === "void" ? "void" : "number";
    tsLines.push(`declare function ${name}(${ps.join(", ")}): ${ret};`);
  }
}

/* A file of bare `declare function`s is not a module, so nothing can import
 * it. Each declaration gets an exported wrapper that calls it DIRECTLY --
 * the same shape host/skia-ffi.ts uses, and for the same two reasons: the
 * result is never bound to a local (upstream issue #21 drops the call), and
 * each declaration is called by exactly one wrapper. */
const wrapperLines = ["", "/* Exported wrappers: the declares above are not a module on their own. */"];
for (const line of tsLines) {
  const m = /^declare function (\w+)\(([^)]*)\): (\w+);$/.exec(line);
  if (!m) continue;
  const [, name, params, ret] = m;
  const argNames = params === "" ? [] : params.split(",").map((p) => p.trim().split(":")[0]);
  /* The DECLARATION carries the C symbol name (gen-ffi.js derives the symbol
   * from it), so the EXPORT needs a different one: snake_case -> camelCase,
   * mirroring host/skia-ffi.ts. */
  const exported = name.replace(/^(gl|sg_gl)_?/, "").replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());
  const safe = exported === "" ? name : exported;
  wrapperLines.push(
    `export function ${safe}(${params}): ${ret} { ${ret === "void" ? "" : "return "}${name}(${argNames.join(", ")}); }`,
  );
}
tsLines.push(...wrapperLines);

/* The raw GL entry points are exported by libGLESv2, not by anything in
 * shim/, so gen-ffi.js cannot parse their signatures out of our sources.
 * Hand them over in the shape it expects. */
const glSigs = {};
for (const fn of buckets.passthrough) {
  glSigs[fn.name] = {
    ret: fn.ret,
    params: fn.params.map((p) => p.type),
  };
}
writeFileSync(join(root, "codegen/gl-signatures.json"),
              JSON.stringify(glSigs, null, 2) + "\n");

writeFileSync(join(root, "shim/sg_gl_gen.cpp"), cLines.join("\n") + "\n");
writeFileSync(join(root, "host/gl-ffi.ts"), tsLines.join("\n") + "\n");

console.log(`gen-gl: ${decls.length} GLES3 entry points from ${HEADER}`);
console.log(`  passthrough (no shim): ${buckets.passthrough.length}`);
console.log(`  narrowing wrappers   : ${buckets.narrow.length}`);
console.log(`  manual (pointers)    : ${buckets.manual.length}  <- hand-written as WebGL2 needs them`);
