/* GENERATED by codegen/gen-shim.js from skia_c.hpp. DO NOT EDIT.
 * Regenerate with: node codegen/gen-shim.js [target]
 */

/* Every wrapper returns its FFI call DIRECTLY. Binding the result to a
 * never-reassigned local made the compiler drop the call outright (see
 * docs/SPIKE-RESULTS.md); the generated shape is immune by construction.
 */

declare function sgCanvasClear(h0: number, a1: number): number;
declare function sgCanvasSave(h0: number): number;
declare function sgCanvasRestore(h0: number): number;
declare function sgCanvasReset(h0: number): number;
declare function sgCanvasTranslate(h0: number, a1: number, a2: number): number;
declare function sgCanvasScale(h0: number, a1: number, a2: number): number;
declare function sgCanvasRotate(h0: number, a1: number): number;
declare function sgCanvasResetTransform(h0: number): number;
declare function sgCanvasConcat(h0: number, h1: number): number;
declare function sgCanvasSetTransform(h0: number, h1: number): number;
declare function sgCanvasDrawRect(h0: number, a1: number, a2: number, a3: number, a4: number, h5: number): number;
declare function sgCanvasDrawPath(h0: number, h1: number, h2: number): number;
declare function sgCanvasDrawColor(h0: number, a1: number, a2: number, a3: number, a4: number): number;
declare function sgCanvasClipRect(h0: number, a1: number, a2: number, a3: number, a4: number): number;
declare function sgCanvasClipPath(h0: number, h1: number): number;
declare function sgCanvasDrawSurface(h0: number, h1: number, a2: number, a3: number, a4: number, a5: number, a6: number): number;
declare function sgCanvasDrawSurfaceRect(h0: number, h1: number, a2: number, a3: number, a4: number, a5: number, a6: number, a7: number, a8: number, a9: number, a10: number): number;
declare function sgPaintCreate(unused: number): number;
declare function sgPaintDestroy(h0: number): number;
declare function sgPaintClone(h0: number): number;
declare function sgPaintSetStyle(h0: number, a1: number): number;
declare function sgPaintSetColor(h0: number, a1: number, a2: number, a3: number, a4: number): number;
declare function sgPaintSetAlpha(h0: number, a1: number): number;
declare function sgPaintGetAlpha(h0: number): number;
declare function sgPaintSetAntiAlias(h0: number, a1: number): number;
declare function sgPaintSetBlendMode(h0: number, a1: number): number;
declare function sgPaintGetBlendMode(h0: number): number;
declare function sgPaintSetStrokeWidth(h0: number, a1: number): number;
declare function sgPaintGetStrokeWidth(h0: number): number;
declare function sgPaintSetStrokeCap(h0: number, a1: number): number;
declare function sgPaintGetStrokeCap(h0: number): number;
declare function sgPaintSetStrokeJoin(h0: number, a1: number): number;
declare function sgPaintGetStrokeJoin(h0: number): number;
declare function sgPaintSetStrokeMiter(h0: number, a1: number): number;
declare function sgPaintGetStrokeMiter(h0: number): number;
declare function sgPaintSetImageFilter(h0: number, h1: number): number;
declare function sgPathCreate(unused: number): number;
declare function sgPathDestroy(h0: number): number;
declare function sgPathClone(h0: number): number;
declare function sgPathMoveTo(h0: number, a1: number, a2: number): number;
declare function sgPathLineTo(h0: number, a1: number, a2: number): number;
declare function sgPathCubicTo(h0: number, a1: number, a2: number, a3: number, a4: number, a5: number, a6: number): number;
declare function sgPathQuadTo(h0: number, a1: number, a2: number, a3: number, a4: number): number;
declare function sgPathClose(h0: number): number;
declare function sgPathAddRect(h0: number, a1: number, a2: number, a3: number, a4: number): number;
declare function sgPathAddCircle(h0: number, a1: number, a2: number, a3: number): number;
declare function sgPathArcTo(h0: number, a1: number, a2: number, a3: number, a4: number, a5: number, a6: number, a7: number): number;
declare function sgPathArcToTangent(h0: number, a1: number, a2: number, a3: number, a4: number, a5: number): number;
declare function sgPathSetFillType(h0: number, a1: number): number;
declare function sgPathGetFillType(h0: number): number;
declare function sgPathIsEmpty(h0: number): number;
declare function sgPathHitTest(h0: number, a1: number, a2: number, a3: number): number;
declare function sgPathStrokeHitTest(h0: number, a1: number, a2: number, a3: number): number;
declare function sgPathTransformSelf(h0: number, h1: number): number;
declare function sgPathOp(h0: number, h1: number, a2: number): number;
declare function sgPathSimplify(h0: number): number;
declare function sgPathEquals(h0: number, h1: number): number;
declare function sgPathEffectDestroy(h0: number): number;
declare function sgMatrixCreate(unused: number): number;
declare function sgMatrixNew(a0: number, a1: number, a2: number, a3: number, a4: number, a5: number): number;
declare function sgMatrixClone(h0: number): number;
declare function sgMatrixDestroy(h0: number): number;
declare function sgMatrixPreTranslate(h0: number, a1: number, a2: number): number;
declare function sgMatrixPreScale(h0: number, a1: number, a2: number): number;
declare function sgMatrixPreRotate(h0: number, a1: number): number;
declare function sgMatrixPreConcat(h0: number, h1: number): number;
declare function sgShaderDestroy(h0: number): number;
declare function sgSurfaceCreateRgbaPremultiplied(a0: number, a1: number, a2: number): number;
declare function sgSurfaceCreateRgba(a0: number, a1: number, a2: number): number;
declare function sgSurfaceDestroy(h0: number): number;
declare function sgSurfaceGetCanvas(h0: number): number;
declare function sgSurfaceGetWidth(h0: number): number;
declare function sgSurfaceGetHeight(h0: number): number;
declare function sgSurfaceMakeImageSnapshot(h0: number): number;
declare function sgImageDestroy(h0: number): number;
declare function sgImageGetWidth(h0: number): number;
declare function sgImageGetHeight(h0: number): number;
declare function sgBitmapDestroy(h0: number): number;
declare function sgBitmapGetWidth(h0: number): number;
declare function sgBitmapGetHeight(h0: number): number;
declare function sgImageFilterDestroy(h0: number): number;

export function canvasClear(h0: number, a1: number): number { return sgCanvasClear(h0, a1); }
export function canvasSave(h0: number): number { return sgCanvasSave(h0); }
export function canvasRestore(h0: number): number { return sgCanvasRestore(h0); }
export function canvasReset(h0: number): number { return sgCanvasReset(h0); }
export function canvasTranslate(h0: number, a1: number, a2: number): number { return sgCanvasTranslate(h0, a1, a2); }
export function canvasScale(h0: number, a1: number, a2: number): number { return sgCanvasScale(h0, a1, a2); }
export function canvasRotate(h0: number, a1: number): number { return sgCanvasRotate(h0, a1); }
export function canvasResetTransform(h0: number): number { return sgCanvasResetTransform(h0); }
export function canvasConcat(h0: number, h1: number): number { return sgCanvasConcat(h0, h1); }
export function canvasSetTransform(h0: number, h1: number): number { return sgCanvasSetTransform(h0, h1); }
export function canvasDrawRect(h0: number, a1: number, a2: number, a3: number, a4: number, h5: number): number { return sgCanvasDrawRect(h0, a1, a2, a3, a4, h5); }
export function canvasDrawPath(h0: number, h1: number, h2: number): number { return sgCanvasDrawPath(h0, h1, h2); }
export function canvasDrawColor(h0: number, a1: number, a2: number, a3: number, a4: number): number { return sgCanvasDrawColor(h0, a1, a2, a3, a4); }
export function canvasClipRect(h0: number, a1: number, a2: number, a3: number, a4: number): number { return sgCanvasClipRect(h0, a1, a2, a3, a4); }
export function canvasClipPath(h0: number, h1: number): number { return sgCanvasClipPath(h0, h1); }
export function canvasDrawSurface(h0: number, h1: number, a2: number, a3: number, a4: number, a5: number, a6: number): number { return sgCanvasDrawSurface(h0, h1, a2, a3, a4, a5, a6); }
export function canvasDrawSurfaceRect(h0: number, h1: number, a2: number, a3: number, a4: number, a5: number, a6: number, a7: number, a8: number, a9: number, a10: number): number { return sgCanvasDrawSurfaceRect(h0, h1, a2, a3, a4, a5, a6, a7, a8, a9, a10); }
export function paintCreate(): number { return sgPaintCreate(0); }
export function paintDestroy(h0: number): number { return sgPaintDestroy(h0); }
export function paintClone(h0: number): number { return sgPaintClone(h0); }
export function paintSetStyle(h0: number, a1: number): number { return sgPaintSetStyle(h0, a1); }
export function paintSetColor(h0: number, a1: number, a2: number, a3: number, a4: number): number { return sgPaintSetColor(h0, a1, a2, a3, a4); }
export function paintSetAlpha(h0: number, a1: number): number { return sgPaintSetAlpha(h0, a1); }
export function paintGetAlpha(h0: number): number { return sgPaintGetAlpha(h0); }
export function paintSetAntiAlias(h0: number, a1: number): number { return sgPaintSetAntiAlias(h0, a1); }
export function paintSetBlendMode(h0: number, a1: number): number { return sgPaintSetBlendMode(h0, a1); }
export function paintGetBlendMode(h0: number): number { return sgPaintGetBlendMode(h0); }
export function paintSetStrokeWidth(h0: number, a1: number): number { return sgPaintSetStrokeWidth(h0, a1); }
export function paintGetStrokeWidth(h0: number): number { return sgPaintGetStrokeWidth(h0); }
export function paintSetStrokeCap(h0: number, a1: number): number { return sgPaintSetStrokeCap(h0, a1); }
export function paintGetStrokeCap(h0: number): number { return sgPaintGetStrokeCap(h0); }
export function paintSetStrokeJoin(h0: number, a1: number): number { return sgPaintSetStrokeJoin(h0, a1); }
export function paintGetStrokeJoin(h0: number): number { return sgPaintGetStrokeJoin(h0); }
export function paintSetStrokeMiter(h0: number, a1: number): number { return sgPaintSetStrokeMiter(h0, a1); }
export function paintGetStrokeMiter(h0: number): number { return sgPaintGetStrokeMiter(h0); }
export function paintSetImageFilter(h0: number, h1: number): number { return sgPaintSetImageFilter(h0, h1); }
export function pathCreate(): number { return sgPathCreate(0); }
export function pathDestroy(h0: number): number { return sgPathDestroy(h0); }
export function pathClone(h0: number): number { return sgPathClone(h0); }
export function pathMoveTo(h0: number, a1: number, a2: number): number { return sgPathMoveTo(h0, a1, a2); }
export function pathLineTo(h0: number, a1: number, a2: number): number { return sgPathLineTo(h0, a1, a2); }
export function pathCubicTo(h0: number, a1: number, a2: number, a3: number, a4: number, a5: number, a6: number): number { return sgPathCubicTo(h0, a1, a2, a3, a4, a5, a6); }
export function pathQuadTo(h0: number, a1: number, a2: number, a3: number, a4: number): number { return sgPathQuadTo(h0, a1, a2, a3, a4); }
export function pathClose(h0: number): number { return sgPathClose(h0); }
export function pathAddRect(h0: number, a1: number, a2: number, a3: number, a4: number): number { return sgPathAddRect(h0, a1, a2, a3, a4); }
export function pathAddCircle(h0: number, a1: number, a2: number, a3: number): number { return sgPathAddCircle(h0, a1, a2, a3); }
export function pathArcTo(h0: number, a1: number, a2: number, a3: number, a4: number, a5: number, a6: number, a7: number): number { return sgPathArcTo(h0, a1, a2, a3, a4, a5, a6, a7); }
export function pathArcToTangent(h0: number, a1: number, a2: number, a3: number, a4: number, a5: number): number { return sgPathArcToTangent(h0, a1, a2, a3, a4, a5); }
export function pathSetFillType(h0: number, a1: number): number { return sgPathSetFillType(h0, a1); }
export function pathGetFillType(h0: number): number { return sgPathGetFillType(h0); }
export function pathIsEmpty(h0: number): number { return sgPathIsEmpty(h0); }
export function pathHitTest(h0: number, a1: number, a2: number, a3: number): number { return sgPathHitTest(h0, a1, a2, a3); }
export function pathStrokeHitTest(h0: number, a1: number, a2: number, a3: number): number { return sgPathStrokeHitTest(h0, a1, a2, a3); }
export function pathTransformSelf(h0: number, h1: number): number { return sgPathTransformSelf(h0, h1); }
export function pathOp(h0: number, h1: number, a2: number): number { return sgPathOp(h0, h1, a2); }
export function pathSimplify(h0: number): number { return sgPathSimplify(h0); }
export function pathEquals(h0: number, h1: number): number { return sgPathEquals(h0, h1); }
export function pathEffectDestroy(h0: number): number { return sgPathEffectDestroy(h0); }
export function matrixCreate(): number { return sgMatrixCreate(0); }
export function matrixNew(a0: number, a1: number, a2: number, a3: number, a4: number, a5: number): number { return sgMatrixNew(a0, a1, a2, a3, a4, a5); }
export function matrixClone(h0: number): number { return sgMatrixClone(h0); }
export function matrixDestroy(h0: number): number { return sgMatrixDestroy(h0); }
export function matrixPreTranslate(h0: number, a1: number, a2: number): number { return sgMatrixPreTranslate(h0, a1, a2); }
export function matrixPreScale(h0: number, a1: number, a2: number): number { return sgMatrixPreScale(h0, a1, a2); }
export function matrixPreRotate(h0: number, a1: number): number { return sgMatrixPreRotate(h0, a1); }
export function matrixPreConcat(h0: number, h1: number): number { return sgMatrixPreConcat(h0, h1); }
export function shaderDestroy(h0: number): number { return sgShaderDestroy(h0); }
export function surfaceCreateRgbaPremultiplied(a0: number, a1: number, a2: number): number { return sgSurfaceCreateRgbaPremultiplied(a0, a1, a2); }
export function surfaceCreateRgba(a0: number, a1: number, a2: number): number { return sgSurfaceCreateRgba(a0, a1, a2); }
export function surfaceDestroy(h0: number): number { return sgSurfaceDestroy(h0); }
export function surfaceGetCanvas(h0: number): number { return sgSurfaceGetCanvas(h0); }
export function surfaceGetWidth(h0: number): number { return sgSurfaceGetWidth(h0); }
export function surfaceGetHeight(h0: number): number { return sgSurfaceGetHeight(h0); }
export function surfaceMakeImageSnapshot(h0: number): number { return sgSurfaceMakeImageSnapshot(h0); }
export function imageDestroy(h0: number): number { return sgImageDestroy(h0); }
export function imageGetWidth(h0: number): number { return sgImageGetWidth(h0); }
export function imageGetHeight(h0: number): number { return sgImageGetHeight(h0); }
export function bitmapDestroy(h0: number): number { return sgBitmapDestroy(h0); }
export function bitmapGetWidth(h0: number): number { return sgBitmapGetWidth(h0); }
export function bitmapGetHeight(h0: number): number { return sgBitmapGetHeight(h0); }
export function imageFilterDestroy(h0: number): number { return sgImageFilterDestroy(h0); }
