/* GENERATED by codegen/gen-gl.js from the pinned GLES3 header. Do not edit. */
/*
 * Only the float-taking entry points appear here. Everything else binds
 * straight from the manifest with no wrapper at all.
 *
 * The wrapper exists because scriptc's FFI has no f32 class. Declaring a
 * GLfloat-taking function with f64 params is not an approximation: the two
 * occupy XMM registers differently, so the callee reinterprets the bits and
 * reads garbage. Narrowing at the boundary costs one cvtsd2ss, measured as
 * below noise. See docs/FFI-SHIM.md.
 */
#include <GLES3/gl3.h>

extern "C" {

void sg_gl_blend_color(double a0, double a1, double a2, double a3) {
  glBlendColor((GLfloat)a0, (GLfloat)a1, (GLfloat)a2, (GLfloat)a3);
}

void sg_gl_clear_color(double a0, double a1, double a2, double a3) {
  glClearColor((GLfloat)a0, (GLfloat)a1, (GLfloat)a2, (GLfloat)a3);
}

void sg_gl_clear_depthf(double a0) {
  glClearDepthf((GLfloat)a0);
}

void sg_gl_depth_rangef(double a0, double a1) {
  glDepthRangef((GLfloat)a0, (GLfloat)a1);
}

void sg_gl_line_width(double a0) {
  glLineWidth((GLfloat)a0);
}

void sg_gl_polygon_offset(double a0, double a1) {
  glPolygonOffset((GLfloat)a0, (GLfloat)a1);
}

void sg_gl_sample_coverage(double a0, GLboolean a1) {
  glSampleCoverage((GLfloat)a0, a1);
}

void sg_gl_tex_parameterf(GLenum a0, GLenum a1, double a2) {
  glTexParameterf(a0, a1, (GLfloat)a2);
}

void sg_gl_uniform1f(GLint a0, double a1) {
  glUniform1f(a0, (GLfloat)a1);
}

void sg_gl_uniform2f(GLint a0, double a1, double a2) {
  glUniform2f(a0, (GLfloat)a1, (GLfloat)a2);
}

void sg_gl_uniform3f(GLint a0, double a1, double a2, double a3) {
  glUniform3f(a0, (GLfloat)a1, (GLfloat)a2, (GLfloat)a3);
}

void sg_gl_uniform4f(GLint a0, double a1, double a2, double a3, double a4) {
  glUniform4f(a0, (GLfloat)a1, (GLfloat)a2, (GLfloat)a3, (GLfloat)a4);
}

void sg_gl_vertex_attrib1f(GLuint a0, double a1) {
  glVertexAttrib1f(a0, (GLfloat)a1);
}

void sg_gl_vertex_attrib2f(GLuint a0, double a1, double a2) {
  glVertexAttrib2f(a0, (GLfloat)a1, (GLfloat)a2);
}

void sg_gl_vertex_attrib3f(GLuint a0, double a1, double a2, double a3) {
  glVertexAttrib3f(a0, (GLfloat)a1, (GLfloat)a2, (GLfloat)a3);
}

void sg_gl_vertex_attrib4f(GLuint a0, double a1, double a2, double a3, double a4) {
  glVertexAttrib4f(a0, (GLfloat)a1, (GLfloat)a2, (GLfloat)a3, (GLfloat)a4);
}

void sg_gl_clear_bufferfi(GLenum a0, GLint a1, double a2, GLint a3) {
  glClearBufferfi(a0, a1, (GLfloat)a2, a3);
}

void sg_gl_sampler_parameterf(GLuint a0, GLenum a1, double a2) {
  glSamplerParameterf(a0, a1, (GLfloat)a2);
}

}  // extern "C"
