/* GENERATED by codegen/gen-shim.js from skia_c.hpp. DO NOT EDIT.
 * Regenerate with: node codegen/gen-shim.js [target]
 */

#include "sg_skia.h"

extern "C" int32_t sg_canvas_clear(uint32_t h0, uint32_t a1) {
  skiac_canvas* p0 = (skiac_canvas*)sg_table_get(SG_T_CANVAS, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_canvas_clear(p0, (uint32_t)a1);
  return SG_OK;
}

extern "C" int32_t sg_canvas_save(uint32_t h0) {
  skiac_canvas* p0 = (skiac_canvas*)sg_table_get(SG_T_CANVAS, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_canvas_save(p0);
  return SG_OK;
}

extern "C" int32_t sg_canvas_restore(uint32_t h0) {
  skiac_canvas* p0 = (skiac_canvas*)sg_table_get(SG_T_CANVAS, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_canvas_restore(p0);
  return SG_OK;
}

extern "C" int32_t sg_canvas_reset(uint32_t h0) {
  skiac_canvas* p0 = (skiac_canvas*)sg_table_get(SG_T_CANVAS, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_canvas_reset(p0);
  return SG_OK;
}

extern "C" int32_t sg_canvas_translate(uint32_t h0, double a1, double a2) {
  skiac_canvas* p0 = (skiac_canvas*)sg_table_get(SG_T_CANVAS, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_canvas_translate(p0, (float)a1, (float)a2);
  return SG_OK;
}

extern "C" int32_t sg_canvas_scale(uint32_t h0, double a1, double a2) {
  skiac_canvas* p0 = (skiac_canvas*)sg_table_get(SG_T_CANVAS, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_canvas_scale(p0, (float)a1, (float)a2);
  return SG_OK;
}

extern "C" int32_t sg_canvas_rotate(uint32_t h0, double a1) {
  skiac_canvas* p0 = (skiac_canvas*)sg_table_get(SG_T_CANVAS, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_canvas_rotate(p0, (float)a1);
  return SG_OK;
}

extern "C" int32_t sg_canvas_reset_transform(uint32_t h0) {
  skiac_canvas* p0 = (skiac_canvas*)sg_table_get(SG_T_CANVAS, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_canvas_reset_transform(p0);
  return SG_OK;
}

extern "C" int32_t sg_canvas_concat(uint32_t h0, uint32_t h1) {
  skiac_canvas* p0 = (skiac_canvas*)sg_table_get(SG_T_CANVAS, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_matrix* p1 = (skiac_matrix*)sg_table_get(SG_T_MATRIX, h1);
  if (!p1 && h1 != 0) return SG_EBADHANDLE;
  skiac_canvas_concat(p0, p1);
  return SG_OK;
}

extern "C" int32_t sg_canvas_set_transform(uint32_t h0, uint32_t h1) {
  skiac_canvas* p0 = (skiac_canvas*)sg_table_get(SG_T_CANVAS, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_matrix* p1 = (skiac_matrix*)sg_table_get(SG_T_MATRIX, h1);
  if (!p1 && h1 != 0) return SG_EBADHANDLE;
  skiac_canvas_set_transform(p0, p1);
  return SG_OK;
}

extern "C" int32_t sg_canvas_draw_rect(uint32_t h0, double a1, double a2, double a3, double a4, uint32_t h5) {
  skiac_canvas* p0 = (skiac_canvas*)sg_table_get(SG_T_CANVAS, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_paint* p5 = (skiac_paint*)sg_table_get(SG_T_PAINT, h5);
  if (!p5 && h5 != 0) return SG_EBADHANDLE;
  skiac_canvas_draw_rect(p0, (float)a1, (float)a2, (float)a3, (float)a4, p5);
  return SG_OK;
}

extern "C" int32_t sg_canvas_draw_path(uint32_t h0, uint32_t h1, uint32_t h2) {
  skiac_canvas* p0 = (skiac_canvas*)sg_table_get(SG_T_CANVAS, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_path* p1 = (skiac_path*)sg_table_get(SG_T_PATH, h1);
  if (!p1 && h1 != 0) return SG_EBADHANDLE;
  skiac_paint* p2 = (skiac_paint*)sg_table_get(SG_T_PAINT, h2);
  if (!p2 && h2 != 0) return SG_EBADHANDLE;
  skiac_canvas_draw_path(p0, p1, p2);
  return SG_OK;
}

extern "C" int32_t sg_canvas_draw_color(uint32_t h0, double a1, double a2, double a3, double a4) {
  skiac_canvas* p0 = (skiac_canvas*)sg_table_get(SG_T_CANVAS, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_canvas_draw_color(p0, (float)a1, (float)a2, (float)a3, (float)a4);
  return SG_OK;
}

extern "C" int32_t sg_canvas_clip_rect(uint32_t h0, double a1, double a2, double a3, double a4) {
  skiac_canvas* p0 = (skiac_canvas*)sg_table_get(SG_T_CANVAS, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_canvas_clip_rect(p0, (float)a1, (float)a2, (float)a3, (float)a4);
  return SG_OK;
}

extern "C" int32_t sg_canvas_clip_path(uint32_t h0, uint32_t h1) {
  skiac_canvas* p0 = (skiac_canvas*)sg_table_get(SG_T_CANVAS, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_path* p1 = (skiac_path*)sg_table_get(SG_T_PATH, h1);
  if (!p1 && h1 != 0) return SG_EBADHANDLE;
  skiac_canvas_clip_path(p0, p1);
  return SG_OK;
}

extern "C" int32_t sg_canvas_draw_surface(uint32_t h0, uint32_t h1, double a2, double a3, uint32_t a4, int32_t a5, int32_t a6) {
  skiac_canvas* p0 = (skiac_canvas*)sg_table_get(SG_T_CANVAS, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_surface* p1 = (skiac_surface*)sg_table_get(SG_T_SURFACE, h1);
  if (!p1 && h1 != 0) return SG_EBADHANDLE;
  skiac_canvas_draw_surface(p0, p1, (float)a2, (float)a3, (uint8_t)a4, (int)a5, (int)a6);
  return SG_OK;
}

extern "C" int32_t sg_canvas_draw_surface_rect(uint32_t h0, uint32_t h1, double a2, double a3, double a4, double a5, double a6, double a7, double a8, double a9, int32_t a10) {
  skiac_canvas* p0 = (skiac_canvas*)sg_table_get(SG_T_CANVAS, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_surface* p1 = (skiac_surface*)sg_table_get(SG_T_SURFACE, h1);
  if (!p1 && h1 != 0) return SG_EBADHANDLE;
  skiac_canvas_draw_surface_rect(p0, p1, (float)a2, (float)a3, (float)a4, (float)a5, (float)a6, (float)a7, (float)a8, (float)a9, (int)a10);
  return SG_OK;
}

extern "C" uint32_t sg_paint_create(int32_t unused) {
  (void)unused;
  return sg_table_alloc(SG_T_PAINT, (void*)skiac_paint_create());
}

extern "C" int32_t sg_paint_destroy(uint32_t h0) {
  skiac_paint* p0 = (skiac_paint*)sg_table_take(SG_T_PAINT, h0);
  if (!p0) return SG_OK;
  skiac_paint_destroy(p0);
  return SG_OK;
}

extern "C" uint32_t sg_paint_clone(uint32_t h0) {
  skiac_paint* p0 = (skiac_paint*)sg_table_get(SG_T_PAINT, h0);
  if (!p0 && h0 != 0) return 0;
  return sg_table_alloc(SG_T_PAINT, (void*)skiac_paint_clone(p0));
}

extern "C" int32_t sg_paint_set_style(uint32_t h0, int32_t a1) {
  skiac_paint* p0 = (skiac_paint*)sg_table_get(SG_T_PAINT, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_paint_set_style(p0, (int)a1);
  return SG_OK;
}

extern "C" int32_t sg_paint_set_color(uint32_t h0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4) {
  skiac_paint* p0 = (skiac_paint*)sg_table_get(SG_T_PAINT, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_paint_set_color(p0, (uint8_t)a1, (uint8_t)a2, (uint8_t)a3, (uint8_t)a4);
  return SG_OK;
}

extern "C" int32_t sg_paint_set_alpha(uint32_t h0, uint32_t a1) {
  skiac_paint* p0 = (skiac_paint*)sg_table_get(SG_T_PAINT, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_paint_set_alpha(p0, (uint8_t)a1);
  return SG_OK;
}

extern "C" uint32_t sg_paint_get_alpha(uint32_t h0) {
  skiac_paint* p0 = (skiac_paint*)sg_table_get(SG_T_PAINT, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  return (uint32_t)skiac_paint_get_alpha(p0);
}

extern "C" int32_t sg_paint_set_anti_alias(uint32_t h0, uint32_t a1) {
  skiac_paint* p0 = (skiac_paint*)sg_table_get(SG_T_PAINT, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_paint_set_anti_alias(p0, !!a1);
  return SG_OK;
}

extern "C" int32_t sg_paint_set_blend_mode(uint32_t h0, int32_t a1) {
  skiac_paint* p0 = (skiac_paint*)sg_table_get(SG_T_PAINT, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_paint_set_blend_mode(p0, (int)a1);
  return SG_OK;
}

extern "C" int32_t sg_paint_get_blend_mode(uint32_t h0) {
  skiac_paint* p0 = (skiac_paint*)sg_table_get(SG_T_PAINT, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  return (int32_t)skiac_paint_get_blend_mode(p0);
}

extern "C" int32_t sg_paint_set_stroke_width(uint32_t h0, double a1) {
  skiac_paint* p0 = (skiac_paint*)sg_table_get(SG_T_PAINT, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_paint_set_stroke_width(p0, (float)a1);
  return SG_OK;
}

extern "C" double sg_paint_get_stroke_width(uint32_t h0) {
  skiac_paint* p0 = (skiac_paint*)sg_table_get(SG_T_PAINT, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  return (double)skiac_paint_get_stroke_width(p0);
}

extern "C" int32_t sg_paint_set_stroke_cap(uint32_t h0, int32_t a1) {
  skiac_paint* p0 = (skiac_paint*)sg_table_get(SG_T_PAINT, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_paint_set_stroke_cap(p0, (int)a1);
  return SG_OK;
}

extern "C" int32_t sg_paint_get_stroke_cap(uint32_t h0) {
  skiac_paint* p0 = (skiac_paint*)sg_table_get(SG_T_PAINT, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  return (int32_t)skiac_paint_get_stroke_cap(p0);
}

extern "C" int32_t sg_paint_set_stroke_join(uint32_t h0, uint32_t a1) {
  skiac_paint* p0 = (skiac_paint*)sg_table_get(SG_T_PAINT, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_paint_set_stroke_join(p0, (uint8_t)a1);
  return SG_OK;
}

extern "C" uint32_t sg_paint_get_stroke_join(uint32_t h0) {
  skiac_paint* p0 = (skiac_paint*)sg_table_get(SG_T_PAINT, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  return (uint32_t)skiac_paint_get_stroke_join(p0);
}

extern "C" int32_t sg_paint_set_stroke_miter(uint32_t h0, double a1) {
  skiac_paint* p0 = (skiac_paint*)sg_table_get(SG_T_PAINT, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_paint_set_stroke_miter(p0, (float)a1);
  return SG_OK;
}

extern "C" double sg_paint_get_stroke_miter(uint32_t h0) {
  skiac_paint* p0 = (skiac_paint*)sg_table_get(SG_T_PAINT, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  return (double)skiac_paint_get_stroke_miter(p0);
}

extern "C" int32_t sg_paint_set_image_filter(uint32_t h0, uint32_t h1) {
  skiac_paint* p0 = (skiac_paint*)sg_table_get(SG_T_PAINT, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_image_filter* p1 = (skiac_image_filter*)sg_table_get(SG_T_IMAGE_FILTER, h1);
  if (!p1 && h1 != 0) return SG_EBADHANDLE;
  skiac_paint_set_image_filter(p0, p1);
  return SG_OK;
}

extern "C" uint32_t sg_path_create(int32_t unused) {
  (void)unused;
  return sg_table_alloc(SG_T_PATH, (void*)skiac_path_create());
}

extern "C" int32_t sg_path_destroy(uint32_t h0) {
  skiac_path* p0 = (skiac_path*)sg_table_take(SG_T_PATH, h0);
  if (!p0) return SG_OK;
  skiac_path_destroy(p0);
  return SG_OK;
}

extern "C" uint32_t sg_path_clone(uint32_t h0) {
  skiac_path* p0 = (skiac_path*)sg_table_get(SG_T_PATH, h0);
  if (!p0 && h0 != 0) return 0;
  return sg_table_alloc(SG_T_PATH, (void*)skiac_path_clone(p0));
}

extern "C" int32_t sg_path_move_to(uint32_t h0, double a1, double a2) {
  skiac_path* p0 = (skiac_path*)sg_table_get(SG_T_PATH, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_path_move_to(p0, (float)a1, (float)a2);
  return SG_OK;
}

extern "C" int32_t sg_path_line_to(uint32_t h0, double a1, double a2) {
  skiac_path* p0 = (skiac_path*)sg_table_get(SG_T_PATH, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_path_line_to(p0, (float)a1, (float)a2);
  return SG_OK;
}

extern "C" int32_t sg_path_cubic_to(uint32_t h0, double a1, double a2, double a3, double a4, double a5, double a6) {
  skiac_path* p0 = (skiac_path*)sg_table_get(SG_T_PATH, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_path_cubic_to(p0, (float)a1, (float)a2, (float)a3, (float)a4, (float)a5, (float)a6);
  return SG_OK;
}

extern "C" int32_t sg_path_quad_to(uint32_t h0, double a1, double a2, double a3, double a4) {
  skiac_path* p0 = (skiac_path*)sg_table_get(SG_T_PATH, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_path_quad_to(p0, (float)a1, (float)a2, (float)a3, (float)a4);
  return SG_OK;
}

extern "C" int32_t sg_path_close(uint32_t h0) {
  skiac_path* p0 = (skiac_path*)sg_table_get(SG_T_PATH, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_path_close(p0);
  return SG_OK;
}

extern "C" int32_t sg_path_add_rect(uint32_t h0, double a1, double a2, double a3, double a4) {
  skiac_path* p0 = (skiac_path*)sg_table_get(SG_T_PATH, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_path_add_rect(p0, (float)a1, (float)a2, (float)a3, (float)a4);
  return SG_OK;
}

extern "C" int32_t sg_path_add_circle(uint32_t h0, double a1, double a2, double a3) {
  skiac_path* p0 = (skiac_path*)sg_table_get(SG_T_PATH, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_path_add_circle(p0, (float)a1, (float)a2, (float)a3);
  return SG_OK;
}

extern "C" int32_t sg_path_arc_to(uint32_t h0, double a1, double a2, double a3, double a4, double a5, double a6, uint32_t a7) {
  skiac_path* p0 = (skiac_path*)sg_table_get(SG_T_PATH, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_path_arc_to(p0, (float)a1, (float)a2, (float)a3, (float)a4, (float)a5, (float)a6, !!a7);
  return SG_OK;
}

extern "C" int32_t sg_path_arc_to_tangent(uint32_t h0, double a1, double a2, double a3, double a4, double a5) {
  skiac_path* p0 = (skiac_path*)sg_table_get(SG_T_PATH, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_path_arc_to_tangent(p0, (float)a1, (float)a2, (float)a3, (float)a4, (float)a5);
  return SG_OK;
}

extern "C" int32_t sg_path_set_fill_type(uint32_t h0, int32_t a1) {
  skiac_path* p0 = (skiac_path*)sg_table_get(SG_T_PATH, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_path_set_fill_type(p0, (int)a1);
  return SG_OK;
}

extern "C" int32_t sg_path_get_fill_type(uint32_t h0) {
  skiac_path* p0 = (skiac_path*)sg_table_get(SG_T_PATH, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  return (int32_t)skiac_path_get_fill_type(p0);
}

extern "C" uint32_t sg_path_is_empty(uint32_t h0) {
  skiac_path* p0 = (skiac_path*)sg_table_get(SG_T_PATH, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  return (uint32_t)skiac_path_is_empty(p0);
}

extern "C" uint32_t sg_path_hit_test(uint32_t h0, double a1, double a2, int32_t a3) {
  skiac_path* p0 = (skiac_path*)sg_table_get(SG_T_PATH, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  return (uint32_t)skiac_path_hit_test(p0, (float)a1, (float)a2, (int)a3);
}

extern "C" uint32_t sg_path_stroke_hit_test(uint32_t h0, double a1, double a2, double a3) {
  skiac_path* p0 = (skiac_path*)sg_table_get(SG_T_PATH, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  return (uint32_t)skiac_path_stroke_hit_test(p0, (float)a1, (float)a2, (float)a3);
}

extern "C" int32_t sg_path_transform_self(uint32_t h0, uint32_t h1) {
  skiac_path* p0 = (skiac_path*)sg_table_get(SG_T_PATH, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_matrix* p1 = (skiac_matrix*)sg_table_get(SG_T_MATRIX, h1);
  if (!p1 && h1 != 0) return SG_EBADHANDLE;
  skiac_path_transform_self(p0, p1);
  return SG_OK;
}

extern "C" uint32_t sg_path_op(uint32_t h0, uint32_t h1, int32_t a2) {
  skiac_path* p0 = (skiac_path*)sg_table_get(SG_T_PATH, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_path* p1 = (skiac_path*)sg_table_get(SG_T_PATH, h1);
  if (!p1 && h1 != 0) return SG_EBADHANDLE;
  return (uint32_t)skiac_path_op(p0, p1, (int)a2);
}

extern "C" uint32_t sg_path_simplify(uint32_t h0) {
  skiac_path* p0 = (skiac_path*)sg_table_get(SG_T_PATH, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  return (uint32_t)skiac_path_simplify(p0);
}

extern "C" uint32_t sg_path_equals(uint32_t h0, uint32_t h1) {
  skiac_path* p0 = (skiac_path*)sg_table_get(SG_T_PATH, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_path* p1 = (skiac_path*)sg_table_get(SG_T_PATH, h1);
  if (!p1 && h1 != 0) return SG_EBADHANDLE;
  return (uint32_t)skiac_path_equals(p0, p1);
}

extern "C" int32_t sg_path_effect_destroy(uint32_t h0) {
  skiac_path_effect* p0 = (skiac_path_effect*)sg_table_take(SG_T_PATH_EFFECT, h0);
  if (!p0) return SG_OK;
  skiac_path_effect_destroy(p0);
  return SG_OK;
}

extern "C" uint32_t sg_matrix_create(int32_t unused) {
  (void)unused;
  return sg_table_alloc(SG_T_MATRIX, (void*)skiac_matrix_create());
}

extern "C" uint32_t sg_matrix_new(double a0, double a1, double a2, double a3, double a4, double a5) {
  return sg_table_alloc(SG_T_MATRIX, (void*)skiac_matrix_new((float)a0, (float)a1, (float)a2, (float)a3, (float)a4, (float)a5));
}

extern "C" uint32_t sg_matrix_clone(uint32_t h0) {
  skiac_matrix* p0 = (skiac_matrix*)sg_table_get(SG_T_MATRIX, h0);
  if (!p0 && h0 != 0) return 0;
  return sg_table_alloc(SG_T_MATRIX, (void*)skiac_matrix_clone(p0));
}

extern "C" int32_t sg_matrix_destroy(uint32_t h0) {
  skiac_matrix* p0 = (skiac_matrix*)sg_table_take(SG_T_MATRIX, h0);
  if (!p0) return SG_OK;
  skiac_matrix_destroy(p0);
  return SG_OK;
}

extern "C" int32_t sg_matrix_pre_translate(uint32_t h0, double a1, double a2) {
  skiac_matrix* p0 = (skiac_matrix*)sg_table_get(SG_T_MATRIX, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_matrix_pre_translate(p0, (float)a1, (float)a2);
  return SG_OK;
}

extern "C" int32_t sg_matrix_pre_scale(uint32_t h0, double a1, double a2) {
  skiac_matrix* p0 = (skiac_matrix*)sg_table_get(SG_T_MATRIX, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_matrix_pre_scale(p0, (float)a1, (float)a2);
  return SG_OK;
}

extern "C" int32_t sg_matrix_pre_rotate(uint32_t h0, double a1) {
  skiac_matrix* p0 = (skiac_matrix*)sg_table_get(SG_T_MATRIX, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_matrix_pre_rotate(p0, (float)a1);
  return SG_OK;
}

extern "C" int32_t sg_matrix_pre_concat(uint32_t h0, uint32_t h1) {
  skiac_matrix* p0 = (skiac_matrix*)sg_table_get(SG_T_MATRIX, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  skiac_matrix* p1 = (skiac_matrix*)sg_table_get(SG_T_MATRIX, h1);
  if (!p1 && h1 != 0) return SG_EBADHANDLE;
  skiac_matrix_pre_concat(p0, p1);
  return SG_OK;
}

extern "C" int32_t sg_shader_destroy(uint32_t h0) {
  skiac_shader* p0 = (skiac_shader*)sg_table_take(SG_T_SHADER, h0);
  if (!p0) return SG_OK;
  skiac_shader_destroy(p0);
  return SG_OK;
}

extern "C" uint32_t sg_surface_create_rgba_premultiplied(int32_t a0, int32_t a1, uint32_t a2) {
  return sg_table_alloc(SG_T_SURFACE, (void*)skiac_surface_create_rgba_premultiplied((int)a0, (int)a1, (uint8_t)a2));
}

extern "C" uint32_t sg_surface_create_rgba(int32_t a0, int32_t a1, uint32_t a2) {
  return sg_table_alloc(SG_T_SURFACE, (void*)skiac_surface_create_rgba((int)a0, (int)a1, (uint8_t)a2));
}

extern "C" int32_t sg_surface_destroy(uint32_t h0) {
  skiac_surface* p0 = (skiac_surface*)sg_table_take(SG_T_SURFACE, h0);
  if (!p0) return SG_OK;
  skiac_surface_destroy(p0);
  return SG_OK;
}

extern "C" uint32_t sg_surface_get_canvas(uint32_t h0) {
  skiac_surface* p0 = (skiac_surface*)sg_table_get(SG_T_SURFACE, h0);
  if (!p0 && h0 != 0) return 0;
  return sg_table_alloc(SG_T_CANVAS, (void*)skiac_surface_get_canvas(p0));
}

extern "C" int32_t sg_surface_get_width(uint32_t h0) {
  skiac_surface* p0 = (skiac_surface*)sg_table_get(SG_T_SURFACE, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  return (int32_t)skiac_surface_get_width(p0);
}

extern "C" int32_t sg_surface_get_height(uint32_t h0) {
  skiac_surface* p0 = (skiac_surface*)sg_table_get(SG_T_SURFACE, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  return (int32_t)skiac_surface_get_height(p0);
}

extern "C" uint32_t sg_surface_make_image_snapshot(uint32_t h0) {
  skiac_surface* p0 = (skiac_surface*)sg_table_get(SG_T_SURFACE, h0);
  if (!p0 && h0 != 0) return 0;
  return sg_table_alloc(SG_T_IMAGE, (void*)skiac_surface_make_image_snapshot(p0));
}

extern "C" int32_t sg_image_destroy(uint32_t h0) {
  skiac_image* p0 = (skiac_image*)sg_table_take(SG_T_IMAGE, h0);
  if (!p0) return SG_OK;
  skiac_image_destroy(p0);
  return SG_OK;
}

extern "C" int32_t sg_image_get_width(uint32_t h0) {
  skiac_image* p0 = (skiac_image*)sg_table_get(SG_T_IMAGE, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  return (int32_t)skiac_image_get_width(p0);
}

extern "C" int32_t sg_image_get_height(uint32_t h0) {
  skiac_image* p0 = (skiac_image*)sg_table_get(SG_T_IMAGE, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  return (int32_t)skiac_image_get_height(p0);
}

extern "C" int32_t sg_bitmap_destroy(uint32_t h0) {
  skiac_bitmap* p0 = (skiac_bitmap*)sg_table_take(SG_T_BITMAP, h0);
  if (!p0) return SG_OK;
  skiac_bitmap_destroy(p0);
  return SG_OK;
}

extern "C" uint32_t sg_bitmap_get_width(uint32_t h0) {
  skiac_bitmap* p0 = (skiac_bitmap*)sg_table_get(SG_T_BITMAP, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  return (uint32_t)skiac_bitmap_get_width(p0);
}

extern "C" uint32_t sg_bitmap_get_height(uint32_t h0) {
  skiac_bitmap* p0 = (skiac_bitmap*)sg_table_get(SG_T_BITMAP, h0);
  if (!p0 && h0 != 0) return SG_EBADHANDLE;
  return (uint32_t)skiac_bitmap_get_height(p0);
}

extern "C" int32_t sg_image_filter_destroy(uint32_t h0) {
  skiac_image_filter* p0 = (skiac_image_filter*)sg_table_take(SG_T_IMAGE_FILTER, h0);
  if (!p0) return SG_OK;
  skiac_image_filter_destroy(p0);
  return SG_OK;
}
