/* GENERATED by codegen/gen-entry.js. DO NOT EDIT.
 *
 * Regenerate by building the game: scripts/build.sh <gameDir>
 *
 * The order below is the whole point, and it mirrors a browser page:
 *
 *   1. boot()  opens the window, so a live canvas exists
 *   2. the game module is evaluated -- its top level runs here
 *   3. run()   fires 'load', then drives requestAnimationFrame forever
 *
 * ES imports are HOISTED, so step 2 actually happens before step 1's
 * statement is reached. That is exactly why setup belongs in a 'load'
 * handler (window.onLoad) rather than at a module's top level -- the same
 * rule a page follows.
 */
import { boot, run, HostOptions, optionsFromEnv } from "../../../host/runtime.js";

const opts = optionsFromEnv(new HostOptions());
opts.width = 480;
opts.height = 270;
/* The web root, baked in at build time.
 *
 * NOT derived from argv[1]: the binary lives in build/ while its assets live
 * with the source, so deriving the root from the executable's directory
 * silently loads nothing. SG_GAME_DIR overrides for a shipped bundle that
 * sits beside its assets. */
opts.gameDir = process.env["SG_GAME_DIR"] ?? "examples/minimal";

const brc = boot(opts);
if (brc !== 0) process.exit(brc);

import "../main.js";

process.exit(run(opts));
